version: '3.8'

services:
  backend:
    build:
      context: ./employee-records-management-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./swing-ui
    environment:
      - DISPLAY=host.docker.internal:0
      - API_BACKEND=http://backend:8080
    networks:
      - app-network
    depends_on:
      - backend
    command: ["sh", "-c", "java -Djava.awt.headless=false -jar /frontend-employee-records-management.jar"]

networks:
  app-network:
    driver: bridge
